# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "feeds-app"
client_id = "f2a5a296a5f9330e57b2a500092a5b4c"
application_url = "https://deputy-rr-macedonia-employee.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://deputy-rr-macedonia-employee.trycloudflare.com/auth/callback",
  "https://deputy-rr-macedonia-employee.trycloudflare.com/auth/shopify/callback",
  "https://deputy-rr-macedonia-employee.trycloudflare.com/api/auth/callback",
  "https://deputy-rr-macedonia-employee.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "teststore2055.myshopify.com"
