# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "feed-app"
client_id = "a8617de2becf621ba73df613fc053cb4"
application_url = "https://bd-remains-gates-publishing.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://bd-remains-gates-publishing.trycloudflare.com/auth/callback",
  "https://bd-remains-gates-publishing.trycloudflare.com/auth/shopify/callback",
  "https://bd-remains-gates-publishing.trycloudflare.com/api/auth/callback",
  "https://bd-remains-gates-publishing.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "teststore2055.myshopify.com"
