# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ae7ec1a608904c8460207757b61c9d38"
name = "feed-app"
application_url = "https://ae-acrylic-applications-contributors.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-saurav-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_price_rules,write_price_rules,write_discounts"

[auth]
redirect_urls = [
  "https://ae-acrylic-applications-contributors.trycloudflare.com/auth/callback",
  "https://ae-acrylic-applications-contributors.trycloudflare.com/auth/shopify/callback",
  "https://ae-acrylic-applications-contributors.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
