# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ae7ec1a608904c8460207757b61c9d38"
name = "feed-app"
application_url = "https://studio-principles-licking-secondary.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-saurav-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_price_rules,write_discounts,write_price_rules,write_products"

[auth]
redirect_urls = [
  "https://studio-principles-licking-secondary.trycloudflare.com/auth/callback",
  "https://studio-principles-licking-secondary.trycloudflare.com/auth/shopify/callback",
  "https://studio-principles-licking-secondary.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
